name: phapthoai
description: "Pháp thoại Sư Ông làng mai."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_session: ^0.1.21
  google_fonts: ^6.1.0
  provider: ^6.1.1
  url_launcher: ^6.3.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  shared_preferences: ^2.3.0
  path_provider:
  dio:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "web/favicon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/bg1.jpeg
    - assets/bg2.jpeg
    - assets/langmai.png
    - assets/langmai_1.png
    - assets/langmai_2.png
